### Decision Tree

> Classification algorithm

> It follows tree like a struture to predict the o/p

<img src="https://miro.medium.com/v2/resize:fit:1430/1*rSQIIAboJftqAv_BReNipg.png">

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_excel("/content/tennis_anyone_1000.xlsx")

In [ ]:
df.head()

  Day ID   Outlook Temperature Humidity    Wind Play Tennis
0  Day_1  Overcast        Cool   Normal  Strong         Yes
1  Day_2      Rain        Mild     High    Weak         Yes
2  Day_3  Overcast         Hot   Normal    Weak         Yes
3  Day_4     Sunny        Mild   Normal  Strong         Yes
4  Day_5     Sunny        Mild     High    Weak          No

In [ ]:
df.columns

Index(['Day ID', 'Outlook', 'Temperature', 'Humidity', 'Wind', 'Play Tennis'], dtype='object')

In [ ]:
df.drop(columns='Day ID',inplace=True)

In [ ]:
df.head()

    Outlook Temperature Humidity    Wind Play Tennis
0  Overcast        Cool   Normal  Strong         Yes
1      Rain        Mild     High    Weak         Yes
2  Overcast         Hot   Normal    Weak         Yes
3     Sunny        Mild   Normal  Strong         Yes
4     Sunny        Mild     High    Weak          No

In [ ]:
df.nunique()

Outlook        3
Temperature    3
Humidity       2
Wind           2
Play Tennis    2
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Outlook']=le.fit_transform(df['Outlook'])
df['Temperature']=le.fit_transform(df['Temperature'])
df['Humidity']=le.fit_transform(df['Humidity'])
df['Wind']=le.fit_transform(df['Wind'])
df['Play Tennis']=le.fit_transform(df['Play Tennis'])

In [ ]:
df.columns

Index(['Outlook', 'Temperature', 'Humidity', 'Wind', 'Play Tennis'], dtype='object')

In [ ]:
df.head()

   Outlook  Temperature  Humidity  Wind  Play Tennis
0        0            0         1     0            1
1        1            2         0     1            1
2        0            1         1     1            1
3        2            2         1     0            1
4        2            2         0     1            0

In [ ]:
### Renaming the columns
df.rename(columns={'Play Tennis':'Play Tennis'},inplace=True)

In [ ]:
df['Play Tennis'].value_counts()

Play Tennis
1    651
0    349
Name: count, dtype: int64

In [ ]:
df.shape

(1000, 5)

In [ ]:
x = df.iloc[:,0:-1]
y = df.iloc[:,-1]

In [ ]:
### Splitting dataset Horizointally(train and test set(20%))
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [ ]:
### using Decision Tree model
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt

DecisionTreeClassifier()

In [ ]:
#Training the model
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
### predict the model

predict = dt.predict(x_test)

In [ ]:
### Evaluation of the model
from sklearn.metrics import classification_report

print(classification_report(y_test,predict))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        69
           1       1.00      1.00      1.00       131

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

>>Decision Tree with Accuracy of 100%